
[features]
seeds = false
skip-lint = false

[programs.localnet]
smartpay_rewards = "SmartPayRewards111111111111111111111111111"

[programs.devnet]  
smartpay_rewards = "SmartPayRewards111111111111111111111111111"

[programs.mainnet]
smartpay_rewards = "SmartPayRewards111111111111111111111111111"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
